### ISSUE TITLE
Change default of scriptValidation to true

### ISSUE THREAD

**Issue by alexsuter** [axonivy/project-build-plugin#132]
Open Discussion:

Should we not change the default now?

https://github.com/axonivy/project-build-plugin/blob/37b22a9eec4e912fd47454c2051d05de0e6339ef/src/main/java/ch/ivyteam/ivy/maven/compile/CompileProjectMojo.java#L56

**Comment by alexsuter** [comment]
and there is compilerWarnings

https://axonivy.github.io/project-build-plugin/release/9.3/compileProject-mojo.html#compilerWarnings

is compilerWarnings for java code? and skipScriptValidation for ivyscript?

Maybe we should use more expressive names here?

**Comment by ivy-rew** [comment]
I think the 'skip' = false flag was introduced a such since we had problems in our own demo projects that we coudn't overcome back then. Furthermore, we thought it too dangerous as it was introduced shortly around the first official release of 8.0 LTS:

However, now we are on the leading edge train. We should have enabled this actually with 9.1 already. So yes, make it true :)

**Comment by ivy-rew** [comment]
CompilerWarnings = technical JDT stuff
SkipScriptValidation = ivy internal script magic
If we find a better name I'm open to that. However, the defaults should be as such, that in 99% users don't need to know these flags anyway. So I'd not invest too much into this
